import { Module } from '@nestjs/common';
import { DrizzleModule } from '@/_db/drizzle/drizzle.module';
import { MediaRepositoryModule } from '@/_repositories/providers/media/media.repository/media.repository.module';
import { AdminAuthGuardModule } from '@/common/guards/admin-auth-guard/admin-auth-guard.module';
import { InventoryModule } from '@/modules/inventory/inventory.module';
import { ShopModule } from '@/modules/shop/shop.module';
import { PlantPublishValidator } from './application/plant-publish.validator';
import {
  CreateCategoryCommand,
  CreatePlantCommand,
  CreateTagCommand,
  CreateTagGroupCommand,
  DeleteCategoryCommand,
  DeleteCategoryTranslationCommand,
  DeleteTagCommand,
  DeleteTagGroupCommand,
  DeleteTagGroupTranslationCommand,
  DeleteTagTranslationCommand,
  UpdateCategoryCommand,
  UpdatePlantCommand,
  UpdateTagCommand,
  UpdateTagGroupCommand,
  UpsertCategoryTranslationCommand,
  UpsertTagGroupTranslationCommand,
  UpsertTagTranslationCommand,
} from './application/commands';
import {
  CatalogQueryService,
  GetAdminCategoryAncestorsQuery,
  GetAdminCategoryByIdQuery,
  GetAdminCategoryTreeQuery,
  GetAdminTagByIdQuery,
  GetAdminTagGroupByIdQuery,
  ListAdminCategoriesQuery,
  ListAdminTagGroupsQuery,
  ListAdminTagsQuery,
  ListCategoryTranslationsQuery,
  ListTagGroupTranslationsQuery,
  ListTagTranslationsQuery,
  ListPublicCategoriesQuery,
  GetPublicCategoryByIdQuery,
  GetPublicCategoryTreeQuery,
  ListPublicTagsQuery,
  GetPublicTagByIdQuery,
  ListSellerProductsQuery,
  GetSellerProductByIdQuery,
  GetSellerProductSummaryQuery,
  GetSellerProductOverviewQuery,
} from './application/queries';
import {
  AdminCategoriesController,
  AdminTagGroupsController,
  AdminTagsController,
  PublicCategoriesController,
  PublicTagsController,
  SellerProductsController,
} from './controllers';
import {
  CategoryAdminRepository,
  CategoryHierarchyRepository,
  CategoryRepository,
  ProductRepository,
  TagAdminRepository,
  TagGroupAdminRepository,
  TagGroupRepository,
  TagRepository,
} from './repositories';

@Module({
  imports: [
    DrizzleModule,
    AdminAuthGuardModule,
    ShopModule,
    MediaRepositoryModule,
    InventoryModule,
  ],
  controllers: [
    AdminCategoriesController,
    AdminTagsController,
    AdminTagGroupsController,
    PublicCategoriesController,
    PublicTagsController,
    SellerProductsController,
  ],
  providers: [
    CategoryRepository,
    CategoryHierarchyRepository,
    CategoryAdminRepository,
    TagRepository,
    TagAdminRepository,
    TagGroupRepository,
    TagGroupAdminRepository,
    ProductRepository,
    CatalogQueryService,
    ListAdminCategoriesQuery,
    GetAdminCategoryTreeQuery,
    GetAdminCategoryByIdQuery,
    GetAdminCategoryAncestorsQuery,
    ListCategoryTranslationsQuery,
    ListAdminTagsQuery,
    GetAdminTagByIdQuery,
    ListTagTranslationsQuery,
    ListAdminTagGroupsQuery,
    GetAdminTagGroupByIdQuery,
    ListTagGroupTranslationsQuery,
    ListPublicCategoriesQuery,
    GetPublicCategoryByIdQuery,
    GetPublicCategoryTreeQuery,
    ListPublicTagsQuery,
    GetPublicTagByIdQuery,
    ListSellerProductsQuery,
    GetSellerProductByIdQuery,
    GetSellerProductSummaryQuery,
    GetSellerProductOverviewQuery,
    PlantPublishValidator,
    CreatePlantCommand,
    UpdatePlantCommand,
    CreateCategoryCommand,
    UpdateCategoryCommand,
    DeleteCategoryCommand,
    UpsertCategoryTranslationCommand,
    DeleteCategoryTranslationCommand,
    CreateTagCommand,
    UpdateTagCommand,
    DeleteTagCommand,
    UpsertTagTranslationCommand,
    DeleteTagTranslationCommand,
    CreateTagGroupCommand,
    UpdateTagGroupCommand,
    DeleteTagGroupCommand,
    UpsertTagGroupTranslationCommand,
    DeleteTagGroupTranslationCommand,
  ],
  exports: [
    CatalogQueryService,
    CreatePlantCommand,
    UpdatePlantCommand,
    PlantPublishValidator,
    // Temporary: seller plants still inject category/tag repos until plant migrate.
    CategoryRepository,
    CategoryHierarchyRepository,
    TagRepository,
    TagGroupRepository,
  ],
})
export class CatalogModule {}
