import { Module } from '@nestjs/common';
import { DrizzleModule } from '@/_db/drizzle/drizzle.module';
import { MediaRepositoryModule } from '@/_repositories/providers/media/media.repository/media.repository.module';
import { AdminAuthGuardModule } from '@/common/guards/admin-auth-guard/admin-auth-guard.module';
import { SellerShopGuardModule } from '@/common/guards/seller-shop-guard/seller-shop.guard.module';
import {
  ApplyAsSellerCommand,
  ApproveShopCommand,
  BulkUpdateShippingRatesCommand,
  DeactivateShopCommand,
  DeleteShopCommand,
  FollowShopCommand,
  ReactivateShopCommand,
  RejectShopCommand,
  ReplaceValuePointsCommand,
  ReplaceWhyChooseUsCommand,
  SubmitShopForReviewCommand,
  SuspendShopCommand,
  UnfollowShopCommand,
  UpdateMyShopAddressCommand,
  UpdateMyShopBrandingCommand,
  UpdateMyShopCommand,
  UpdateStorefrontProfileCommand,
  UpdateVerificationDocumentsCommand,
  UploadShopImagesCommand,
  UpsertMyShopContactCommand,
  UpsertMyShopInfoCommand,
} from './application/commands';
import { ShopProfileSectionService } from './application/shop-profile-section.service';
import {
  GetAdminShopByIdQuery,
  GetMyShopQuery,
  GetMyShopVerificationQuery,
  GetMyVerificationHistoryQuery,
  GetPendingVerificationsQuery,
  GetShippingRatesQuery,
  GetShopStatsQuery,
  GetShopStatusQuery,
  GetShopVerificationDetailsQuery,
  GetStorefrontQuery,
  ListAdminShopsQuery,
  ListFollowingShopsQuery,
} from './application/queries';
import {
  AdminShopsController,
  BuyerShopFollowController,
  SellerShippingRatesController,
  SellerShopProfileController,
  SellerStorefrontController,
} from './controllers';
import {
  ShopFollowRepository,
  ShopRepository,
  ShopShippingRatesRepository,
  ShopStorefrontRepository,
  ShopVerificationHistoryRepository,
  ShopVerificationRepository,
} from './repositories';

@Module({
  imports: [
    DrizzleModule,
    MediaRepositoryModule,
    AdminAuthGuardModule,
    // VerifiedUserAuthGuardModule is @Global in AppModule — do not import here
    // (circular: VerifiedUserAuthGuardModule → ShopModule).
    SellerShopGuardModule,
  ],
  controllers: [
    SellerShopProfileController,
    SellerStorefrontController,
    SellerShippingRatesController,
    BuyerShopFollowController,
    AdminShopsController,
  ],
  providers: [
    ShopRepository,
    ShopVerificationRepository,
    ShopVerificationHistoryRepository,
    ShopStorefrontRepository,
    ShopShippingRatesRepository,
    ShopFollowRepository,
    ShopProfileSectionService,
    GetShopStatusQuery,
    GetMyShopQuery,
    GetMyShopVerificationQuery,
    GetMyVerificationHistoryQuery,
    GetStorefrontQuery,
    GetShippingRatesQuery,
    ListFollowingShopsQuery,
    GetPendingVerificationsQuery,
    ListAdminShopsQuery,
    GetAdminShopByIdQuery,
    GetShopStatsQuery,
    GetShopVerificationDetailsQuery,
    ApplyAsSellerCommand,
    UpdateMyShopCommand,
    UpdateMyShopBrandingCommand,
    UpsertMyShopInfoCommand,
    UpsertMyShopContactCommand,
    UpdateMyShopAddressCommand,
    UpdateVerificationDocumentsCommand,
    SubmitShopForReviewCommand,
    UploadShopImagesCommand,
    DeleteShopCommand,
    UpdateStorefrontProfileCommand,
    ReplaceWhyChooseUsCommand,
    ReplaceValuePointsCommand,
    BulkUpdateShippingRatesCommand,
    FollowShopCommand,
    UnfollowShopCommand,
    ApproveShopCommand,
    RejectShopCommand,
    SuspendShopCommand,
    DeactivateShopCommand,
    ReactivateShopCommand,
  ],
  exports: [
    ShopRepository,
    ShopVerificationRepository,
    ShopVerificationHistoryRepository,
    ShopStorefrontRepository,
    ShopShippingRatesRepository,
    ShopFollowRepository,
    GetShopStatusQuery,
    GetMyShopQuery,
    GetStorefrontQuery,
    GetShippingRatesQuery,
    ApplyAsSellerCommand,
    UpdateMyShopCommand,
    UpdateMyShopBrandingCommand,
    UpsertMyShopInfoCommand,
    UpsertMyShopContactCommand,
    UpdateMyShopAddressCommand,
  ],
})
export class ShopModule {}
