import { Module } from '@nestjs/common';
import { DrizzleModule } from '@/_db/drizzle/drizzle.module';
import { MediaModule } from '@/modules/media/media.module';
import {
  ApplyAsSellerCommand,
  ApproveShopCommand,
  BulkUpdateShippingRatesCommand,
  DeactivateShopCommand,
  DeleteShopCommand,
  FollowShopCommand,
  ReactivateShopCommand,
  RejectShopCommand,
  ReplaceValuePointsCommand,
  ReplaceWhyChooseUsCommand,
  SubmitShopForReviewCommand,
  SuspendShopCommand,
  UnfollowShopCommand,
  UpdateMyShopAddressCommand,
  UpdateMyShopBrandingCommand,
  UpdateMyShopCommand,
  UpdateStorefrontProfileCommand,
  UpdateVerificationDocumentsCommand,
  UploadShopImagesCommand,
  UpsertMyShopContactCommand,
  UpsertMyShopInfoCommand,
} from './application/commands';
import { ShopProfileSectionService } from './application/shop-profile-section.service';
import {
  GetAdminShopByIdQuery,
  GetMyShopQuery,
  GetMyShopVerificationQuery,
  GetMyVerificationHistoryQuery,
  GetPendingVerificationsQuery,
  GetPublicShopBySlugQuery,
  GetShippingRatesQuery,
  GetShopCategoriesServedQuery,
  GetShopStatsQuery,
  GetShopStatusQuery,
  GetShopVerificationDetailsQuery,
  GetStorefrontQuery,
  ListAdminShopsQuery,
  ListFollowingShopsQuery,
  ListPublicShopProductsQuery,
  ListPublicShopsQuery,
  ShopQueryService,
} from './application/queries';
import {
  AdminShopsController,
  BuyerShopFollowController,
  PublicShopController,
  SellerShippingRatesController,
  SellerShopProfileController,
  SellerStorefrontController,
} from './controllers';
import {
  ShopFollowRepository,
  ShopRepository,
  ShopShippingRatesRepository,
  ShopStorefrontRepository,
  ShopVerificationHistoryRepository,
  ShopVerificationRepository,
} from './repositories';

@Module({
  imports: [DrizzleModule, MediaModule],
  controllers: [
    PublicShopController,
    SellerShopProfileController,
    SellerStorefrontController,
    SellerShippingRatesController,
    BuyerShopFollowController,
    AdminShopsController,
  ],
  providers: [
    ShopRepository,
    ShopVerificationRepository,
    ShopVerificationHistoryRepository,
    ShopStorefrontRepository,
    ShopShippingRatesRepository,
    ShopFollowRepository,
    ShopProfileSectionService,
    GetShopStatusQuery,
    GetMyShopQuery,
    GetMyShopVerificationQuery,
    GetMyVerificationHistoryQuery,
    GetStorefrontQuery,
    GetShippingRatesQuery,
    ListFollowingShopsQuery,
    ListPublicShopsQuery,
    GetPublicShopBySlugQuery,
    ListPublicShopProductsQuery,
    GetShopCategoriesServedQuery,
    ShopQueryService,
    GetPendingVerificationsQuery,
    ListAdminShopsQuery,
    GetAdminShopByIdQuery,
    GetShopStatsQuery,
    GetShopVerificationDetailsQuery,
    ApplyAsSellerCommand,
    UpdateMyShopCommand,
    UpdateMyShopBrandingCommand,
    UpsertMyShopInfoCommand,
    UpsertMyShopContactCommand,
    UpdateMyShopAddressCommand,
    UpdateVerificationDocumentsCommand,
    SubmitShopForReviewCommand,
    UploadShopImagesCommand,
    DeleteShopCommand,
    UpdateStorefrontProfileCommand,
    ReplaceWhyChooseUsCommand,
    ReplaceValuePointsCommand,
    BulkUpdateShippingRatesCommand,
    FollowShopCommand,
    UnfollowShopCommand,
    ApproveShopCommand,
    RejectShopCommand,
    SuspendShopCommand,
    DeactivateShopCommand,
    ReactivateShopCommand,
  ],
  exports: [
    ShopQueryService,
    ShopVerificationRepository,
    ShopVerificationHistoryRepository,
    ShopStorefrontRepository,
    ShopShippingRatesRepository,
    ShopFollowRepository,
    GetShopStatusQuery,
    GetMyShopQuery,
    GetStorefrontQuery,
    GetShippingRatesQuery,
    ListPublicShopsQuery,
    GetPublicShopBySlugQuery,
    ApplyAsSellerCommand,
    UpdateMyShopCommand,
    UpdateMyShopBrandingCommand,
    UpsertMyShopInfoCommand,
    UpsertMyShopContactCommand,
    UpdateMyShopAddressCommand,
  ],
})
export class ShopModule {}
