import { Module } from '@nestjs/common';
import { DrizzleModule } from '@/_db/drizzle/drizzle.module';
import { ShopModule } from '@/modules/shop/shop.module';
import {
  ApproveArticleCommand,
  ApproveCampaignCommand,
  ArchiveArticleCommand,
  ArchiveCampaignCommand,
  CreateArticleCommand,
  CreateCampaignCommand,
  DeleteArticleCommand,
  DeleteCampaignCommand,
  RejectArticleCommand,
  RejectCampaignCommand,
  SetArticleEditorsPickCommand,
  SubmitArticleCommand,
  SubmitCampaignCommand,
  UpdateArticleCommand,
  UpdateCampaignCommand,
} from './application/commands';
import {
  ContentQueryService,
  GetAdminArticleQuery,
  GetAdminCampaignQuery,
  GetPublicShopArticleQuery,
  GetPublicShopCampaignHighlightsQuery,
  GetPublicShopCampaignQuery,
  GetSellerArticleQuery,
  GetSellerCampaignQuery,
  ListAdminArticlesQuery,
  ListAdminCampaignsQuery,
  ListPublicShopArticlesQuery,
  ListPublicShopCampaignsQuery,
  ListSellerArticlesQuery,
  ListSellerCampaignsQuery,
} from './application/queries';
import {
  AdminArticlesController,
  AdminCampaignsController,
  PublicShopArticlesController,
  PublicShopCampaignsController,
  SellerArticlesController,
  SellerCampaignsController,
} from './controllers';
import { ArticleRepository, CampaignRepository } from './repositories';

@Module({
  imports: [DrizzleModule, ShopModule],
  controllers: [
    SellerArticlesController,
    AdminArticlesController,
    PublicShopArticlesController,
    SellerCampaignsController,
    AdminCampaignsController,
    PublicShopCampaignsController,
  ],
  providers: [
    ArticleRepository,
    CampaignRepository,
    ContentQueryService,
    ListSellerArticlesQuery,
    GetSellerArticleQuery,
    CreateArticleCommand,
    UpdateArticleCommand,
    SubmitArticleCommand,
    ArchiveArticleCommand,
    DeleteArticleCommand,
    ListAdminArticlesQuery,
    GetAdminArticleQuery,
    ApproveArticleCommand,
    RejectArticleCommand,
    SetArticleEditorsPickCommand,
    ListPublicShopArticlesQuery,
    GetPublicShopArticleQuery,
    ListSellerCampaignsQuery,
    GetSellerCampaignQuery,
    CreateCampaignCommand,
    UpdateCampaignCommand,
    SubmitCampaignCommand,
    ArchiveCampaignCommand,
    DeleteCampaignCommand,
    ListAdminCampaignsQuery,
    GetAdminCampaignQuery,
    ApproveCampaignCommand,
    RejectCampaignCommand,
    ListPublicShopCampaignsQuery,
    GetPublicShopCampaignHighlightsQuery,
    GetPublicShopCampaignQuery,
  ],
  exports: [ContentQueryService],
})
export class ContentModule {}
